config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :startdate, presence: true
  validates :enddate, presence: true


  validate :startdate_when_over_the_enddate

  private

  def startdate_when_over_the_enddate
    if startdate != nil? && enddate != nil && startdate > enddate
      errors.add(:startdate,"または終了日に誤りがあります。")  
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    @time = Date.today.strftime('%Y年%m月%d日')
    @taskcount = Task.count
    @tasks = Task.all
  end

  def new
    @task = Task.new
    @time = Date.today.strftime('%Y年%m月%d日')
    
  end

  def create
    @task = Task.new(params.require(:task).permit(:title, :startdate, :enddate, :wholeday, :memo))
    @time = Date.today.strftime('%Y年%m月%d日')
    if @task.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to :tasks
    else
      flash[:alert] = "スケジュールを登録できませんでした。"
      render :new,status: :unprocessable_entity

    end
  end

  def show
    @time = Date.today.strftime('%Y年%m月%d日')
    @task = Task.find(params[:id])
  end

  def edit
    @time = Date.today.strftime('%Y年%m月%d日')
    @task = Task.find(params[:id])
  end

  def update
    @time = Date.today.strftime('%Y年%m月%d日')
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:title, :startdate, :enddate, :wholeday, :memo))
      flash[:notice] = "スケジュールID:#{@task.id}の情報を更新しました"
      redirect_to :tasks
    else
      flash[:alert] = "スケジュールを編集できませんでした。"
      render "edit",status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to :tasks
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <ul>
    <p class = "error">スケジュールを登録できませんでした</p>
  </ul>
<% obj.errors.full_messages.each do |message| %>
  <ul class="error_message">
    <li><%= message %></li>
  </ul>
<% end %>
<% end %>

app/views/shared/_partialfooter.html.erb
<div class = "partialfooter" >
<h4><%="今日は #{@time} です。　スケジュール登録数:#{@taskcount}件" %></h4>
</div>

app/views/shared/_partialfooter2.html.erb
<div class = "partialfooter" >
<h4><%="今日は #{@time} です。" %></h4>
</div>

app/views/shared/_partialheader.html.erb
<div class="partialheader">
   <h4>Ruby on Rails スケジュール管理アプリ</h4>
 </div>

app/views/tasks/edit.html.erb
<header>
<%= render "shared/partialheader" %>
</header>

<h3>登録済みスケジュールの編集</h3>

<%= render "shared/error", obj: @task %>

<%= form_with model: @task do |f| %>
  <div class = edit_table>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :startdate ,"開始日" %></th>
      <td><%= f.date_field :startdate %></td>
    </tr>
    <tr>
      <th><%= f.label :enddate ,"終了日" %></th>
      <td><%= f.date_field :enddate %></td>
    </tr>
    <tr>
      <th><%= f.label :wholeday ,"終日" %></th>
      <td><%= f.check_box :wholeday %><br>終日予定の場合はチェックを入れてください。</td>
    </tr>
    <tr>
    <th><%= f.label :memo ,"メモ" %></th>
    <td><%= f.text_area :memo %> </td>
  </tr>
  </table>

  <div>
    <ul class="edit_li">
      <li class="edit_input"><%= f.submit "編集を完了する" %></li>
      <li><%= link_to "スケジュール一覧に戻る", :tasks %></li>
    </ul>
  </div>
  </div>
<% end %>

<footer>
<%= render "shared/partialfooter2" %>
</footer>

app/views/tasks/index.html.erb
<header>
<%= render "shared/partialheader" %>
</header>

<h3>登録スケジュール一覧</h3>

<% if flash[:notice] %>
  <p class="success"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p class="fail"><%= flash[:alert] %></p>
<% end %>

<div class = "index_table">
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.startdate.strftime('%Y年%m月%d日') %></td>
        <td><%= task.enddate.strftime('%Y年%m月%d日')%></td>
        <td>
          <% if task.wholeday %>
            ○
          <% end %>
        </td>
        <td><%= task.updated_at.to_s(:datetime_jp) %></td>
        <td>
        <%= link_to "参照", task %>
        </td>
        <td>
        <%= link_to "編集", [:edit, task] %>
        </td>
        <td>
        <%= link_to "削除", task, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<p class = "newregister"><%= link_to "スケジュール新規登録", :new_task %></p>

<footer>
<%= render "shared/partialfooter" %>
</footer>

app/views/tasks/new.html.erb
<header>
  <%= render "shared/partialheader" %>
</header>

<h3>スケジュール新規作成</h3>

<%= render "shared/error", obj: @task %>

<%= form_with model: @task do |f| %>
  <table class = "new_table">
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :startdate ,"開始日" %></th>
      <td><%= f.date_field :startdate %></td>
    </tr>

    <tr>
      <th><%= f.label :enddate ,"終了日" %></th>
      <td><%= f.date_field :enddate %></td>
    </tr>

    <tr>
      <th><%= f.label :wholeday ,"終日" %></th>
      <td><%= f.check_box :wholeday %><br>終日予定の場合はチェックを入れてください。</td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>

  </table>

    <ul class="new_li">
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "スケジュール一覧に戻る", :tasks %></li>
    </ul>
<% end %>

<footer>
  <%= render "shared/partialfooter2" %>
</footer>

app/views/tasks/show.html.erb
<header>
  <%= render "shared/partialheader" %>
</header>

<h3>スケジュール詳細</h3>

<div class = "show_table">
<table>
  <tr>
    <th>タイトル</th>
    <td><%= @task.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @task.startdate.strftime('%Y年%m月%d日') %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @task.enddate.strftime('%Y年%m月%d日') %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td>
      <%= "○" if @task.wholeday == true %>
      <%= "" if @task.wholeday == false %>
    </td>
  </tr>
  <tr>
  <th>メモ</th>
  <td><%= @task.memo %></td>
</tr>
</table>

<div class="show_li">
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", :tasks %></li>
  </ul>
  <ul>
    <li><%= link_to "スケジュールを編集する",edit_task_path(@task)  %></li>
  </ul>
  <ul>
    <li><%= link_to "スケジュールを削除する", @task, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %></li>
  </ul>
</div>

<footer>
  <%= render "shared/partialfooter2" %>
</footer>